# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               gansteed
tagline:             'my notes and blogs'
description:         '你的眼睛能看多远'
url:                 /
baseurl:             /
paginate:            8

# About/contact
author:
  name:              gansteed
  url:               http://weibo.com/herozem
  disqus:            gansteed

# Custom vars
saying:              "如果你想成功，那么就去做吧，不必考虑别人的感受， 我是说真的。"

# redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough"]
